---
output: html_document
params:
  indic: "Cases"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message = FALSE, warning = FALSE)
easypackages::libraries("tidyverse", "DT", "sparkline", "here", "zoo", "scales", "RcppRoll")
```

```{r Read CSV, message=FALSE, warning=FALSE}
new_col <- paste("new", tolower(params$indic), sep = "_") %>% 
	ifelse(. == "new_tests", "positivity", .)

pop <- read_csv(here("population", "county.csv"))
cases <- read_csv(here("data", "md_counties_cases.csv")) 
deaths <- read_csv(here("data", "md_counties_deaths.csv"))
daily_tests <- read_csv(here("data", "md_daily_volume_tested_county.csv")) %>% 
	rename(new_tests = value) %>% 
	inner_join(cases, by = c("date", "county", "fips")) %>% 
	mutate(rolling_new_cases = roll_sum(new_cases, 7, align = "right", fill = NA),
				 rolling_new_tests = roll_sum(new_tests, 7, align = "right", fill = NA),
				 positivity = rolling_new_cases/rolling_new_tests) %>% 
	select(county, date, fips, positivity)
population_tested <- read_csv(here("data", "md_population_tested_county.csv")) %>% 
	rename(tests = value) %>% 
	inner_join(cases, by = c("date", "county", "fips")) %>% 
	select(county, date, fips, tests)

tests <- inner_join(daily_tests, population_tested)

totalData <- read_csv(here("data", "md_counties_today_table.csv"))

counties_proper_names <- data.frame(County = c("Allegany", "Anne Arundel", "Baltimore County", "Baltimore City", "Calvert", "Caroline", "Carroll", "Cecil", "Charles", "Dorchester", "Frederick", "Garrett", "Harford", "Howard", "Kent", "Montgomery", "Prince George's", "Queen Anne's", "Somerset", "St. Mary's", "Talbot", "Washington", "Wicomico", "Worcester"), county = cases %>% filter(county != "unknown") %>% pull(county) %>% unique())

trendData <- inner_join(cases, deaths, by = c("county", "date", "fips")) %>%
	inner_join(tests, by = c("county", "date", "fips")) %>%
	select(county, date, new_col)

if (params$indic != "tests") {
	trendData <- trendData %>%
		group_by(county) %>%
		mutate(rolling_avg = rollmeanr(get(new_col), 7, fill = NA)) %>%  # `get()` lets us refer to the column by the string we defined above
		filter(date > max(date) - 14) %>%
		ungroup() %>%
		inner_join(counties_proper_names, by = "county") %>%
		select(County, date, new_col, rolling_avg)
} else {
		trendData <- trendData %>%
		group_by(county) %>%
		mutate(rolling_avg = positivity*100) %>%  # `get()` lets us refer to the column by the string we defined above
		filter(date > max(date) - 14) %>%
		ungroup() %>%
		inner_join(counties_proper_names, by = "county") %>%
		select(County, date, new_col, rolling_avg)
}

```

```{r Trend lines}
trend <- select(trendData, "County", "date", "rolling_avg")
```

```{r}
slColor <- switch(params$indic,
									"Cases" = "#E05F15",
									"Deaths" = "#724654",
									"Tests" = "#E09200")

df <- trend %>% 
    group_by(County) %>% 
    summarize(`14-day trend` = spk_chr(rolling_avg,
                           lineColor = slColor, 
                           fillColor = FALSE,
                           lineWidth = 4,
                           chartRangeMin = 0,
                           chartRangeMax = 10,
                           width = 125,
                           height = 35,
                           highlightLineColor = '', 
                           highlightSpotColor = '',
                           spotColor = '',
                           minSpotColor = '',
                           maxSpotColor = '',
                           disableInteraction = TRUE))
```

```{r}
data <- select(totalData, County, params$indic) %>%
	inner_join(df) %>% 
	inner_join(counties_proper_names, by = "County") %>% 
	inner_join(pop, by = "county") %>% 
	mutate(`Per 100,000 residents` = round(.[[2]]/population*100000)) %>% 
	select(County, 2, `Per 100,000 residents`, `14-day trend`)

if (params$indic == "Tests") {
	data <- inner_join(data, filter(trendData, date == max(date)), by = "County") %>% 
		mutate(rolling_avg = percent(rolling_avg/100, accuracy = 0.01)) %>% 
		select(County, `Population tested` = Tests, `Per 100,000 residents`, `7-day average positivity rate` = rolling_avg)
}
```

```{r}
datatable(data, escape = F, style = 'bootstrap', class = 'table', rownames = FALSE,
					options = list(dom = 't',
												 pageLength = 25,
												 fnDrawCallback = htmlwidgets::JS('function(){
                                              HTMLWidgets.staticRender();
                                              }'))
  ) %>%
	spk_add_deps() %>%
	formatCurrency(c(2, 3), currency = "", interval = 3, mark = ",", digits = 0)
```

